CREATE TABLE `ACESSO` (
 `ID_ROTINA` int DEFAULT NULL,
 `ID_ACESSO` int DEFAULT NULL,
 KEY `ID_ROTINA_FK` (`ID_ROTINA`),
 KEY `ID_ACESSOFKY` (`ID_ACESSO`),
 CONSTRAINT `ID_ACESSOFKY` FOREIGN KEY (`ID_ACESSO`) REFERENCES `CONTROLE_ACESSO` (`ID_ACESSO`),
 CONSTRAINT `ID_ROTINA_FK` FOREIGN KEY (`ID_ROTINA`) REFERENCES `ROTINA` (`ID_ROTINA`)

CREATE TABLE `ARMAZENAMENTOS` (
 `armcodigo` int NOT NULL AUTO_INCREMENT,
 `localizacao` int DEFAULT NULL,
 `prdcodigo` int DEFAULT NULL,
 `nome` varchar(100) DEFAULT NULL,
 `endereco` varchar(8) DEFAULT NULL,
 `capacidade` varchar(100) DEFAULT NULL,
 `dtinstalacao` date DEFAULT NULL,
 `dtmodificacao` date DEFAULT NULL,
 PRIMARY KEY (`armcodigo`),
 KEY `prdcodigo` (`prdcodigo`),
 CONSTRAINT `ARMAZENAMENTOS_ibfk_1` FOREIGN KEY (`prdcodigo`) REFERENCES `PRODUTOS` (`PRDCODIGO`)
);