CREATE TABLE `ACESSO` (
 `ID_ROTINA` int DEFAULT NULL,
 `ID_ACESSO` int DEFAULT NULL,
 KEY `ID_ROTINA_FK` (`ID_ROTINA`),
 KEY `ID_ACESSOFKY` (`ID_ACESSO`),
 CONSTRAINT `ID_ACESSOFKY` FOREIGN KEY (`ID_ACESSO`) REFERENCES `CONTROLE_ACESSO` (`ID_ACESSO`),
 CONSTRAINT `ID_ROTINA_FK` FOREIGN KEY (`ID_ROTINA`) REFERENCES `ROTINA` (`ID_ROTINA`)
);