CREATE TABLE `ACESSO` (
 `ID_ROTINA` int DEFAULT NULL,
 `ID_ACESSO` int DEFAULT NULL,
 KEY `ID_ROTINA_FK` (`ID_ROTINA`),
 KEY `ID_ACESSOFKY` (`ID_ACESSO`),
 CONSTRAINT `ID_ACESSOFKY` FOREIGN KEY (`ID_ACESSO`) REFERENCES `CONTROLE_ACESSO` (`ID_ACESSO`),
 CONSTRAINT `ID_ROTINA_FK` FOREIGN KEY (`ID_ROTINA`) REFERENCES `ROTINA` (`ID_ROTINA`)
);

CREATE TABLE `ARMAZENAMENTOS` (
 `armcodigo` int NOT NULL AUTO_INCREMENT,
 `localizacao` int DEFAULT NULL,
 `prdcodigo` int DEFAULT NULL,
 `nome` varchar(100) DEFAULT NULL,
 `endereco` varchar(8) DEFAULT NULL,
 `capacidade` varchar(100) DEFAULT NULL,
 `dtinstalacao` date DEFAULT NULL,
 `dtmodificacao` date DEFAULT NULL,
 PRIMARY KEY (`armcodigo`),
 KEY `prdcodigo` (`prdcodigo`),
 CONSTRAINT `ARMAZENAMENTOS_ibfk_1` FOREIGN KEY (`prdcodigo`) REFERENCES `PRODUTOS` (`PRDCODIGO`)
);

CREATE TABLE `CARTOES` (
 `CRTCODIGO` int NOT NULL AUTO_INCREMENT,
 `CRTCLIENTE` int DEFAULT NULL,
 `CRTNUMERO` int NOT NULL,
 `CRTTIPO` varchar(50) NOT NULL,
 `CRTEMISSAO` date DEFAULT NULL,
 `CRTVALID` date DEFAULT NULL,
 `CRTSTATUS` varchar(20) DEFAULT NULL,
 `CRTLIMIT` decimal(10,2) DEFAULT NULL,
 `CRTPONT` int DEFAULT '0',
 PRIMARY KEY (`CRTCODIGO`),
 KEY `FK_CRTCLIENTE` (`CRTCLIENTE`),
 CONSTRAINT `FK_CRTCLIENTE` FOREIGN KEY (`CRTCLIENTE`) REFERENCES `CLIENTES` (`CLICODIGO`)
);